# pipeline
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'macos-latest'

variables:
  - group: groupSecretMobileApp
  # buildConfiguration: 'Release'
  # outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

stages:
  - stage: AndroidStage
    displayName: 'Stage: Android stage'
    jobs:
      - job: AndroidJob
        displayName: 'Job: Android job'
        steps:
          # install dotnet core 8
          - task: UseDotNet@2
            displayName: 'Task: Install .Net Core v8'
            inputs:
              packageType: 'sdk'
              version: '8.0.424'

          # install workloads dependencies
          - task: Bash@3
            displayName: 'Task: Install MAUI workloads Android: dotnet workload install android'
            inputs:
              targetType: 'inline'
              script: |
                dotnet nuget locals all --clear
                dotnet workload install android maui-android maccatalyst --source https://aka.ms/dotnet8/nuget/index.json --source https://api.nuget.org/v3/index.json

          # download keystore file
          - task: DownloadSecureFile@1
            displayName: 'Task: Download Keystore File'
            name: keystore_file
            inputs:
              secureFile: 'maui-dotnet-mobile-app.keystore'

          # copy keystore to folder maui project
          - task: CopyFiles@2
            displayName: 'Task Import secure file to project'
            inputs:
              SourceFolder: $(Agent.TempDirectory)
              Contents: 'maui-dotnet-mobile-app.keystore'
              TargetFolder: maui-mobile-app/

          # build maui mobile app
          - task: Bash@3
            displayName: 'Task: Build android maui app'
            inputs:
              targetType: 'inline'
              script: |
                cd maui-mobile-app
                dotnet publish maui-mobile-app.csproj -f net8.0-android -c Release --output '$(Build.ArtifactStagingDirectory)/Android' \
                -p:AndroidKeyStore=true \
                -p:AndroidSigningKeyStore=maui-dotnet-mobile-app.keystore \
                -p:AndroidSigningKeyAlias=maui-dotnet-mobile-app \
                -p:AndroidSigningKeyPass=$(keystorePassword) \
                -p:AndroidSigningStorePass=$(keystorePassword)

          # publish artifact apk
          - task: PublishBuildArtifacts@1
            displayName: 'Task: publish android app to artifacts'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/Android'
              ArtifactName: 'Android'